
"""
for loop same as foreach loop in other tech

for loop depends on a collection that generated by range function

"""

print(list(range(1, 10)))
print(list(range(1, 11)))

print("-" * 40)
for i in range(1, 11):
    print(i, end=" ")
print()

print("-" * 40)
for i in range(1, 31):
    if i % 2 == 0:
        continue
    else:
        print(i, end=" ")
    if  i > 20:
        break
else:
    print("\nCompleted itreation....")

